Feature/metrics
OpenXAIProject/pnpxai pull request #145
Opened 2024-10-15 04:00 UTC by ghkim9213

This PR
- modifies metrics to take external explain function
- removes unnecessary dependencies to explainer from the metrics 
- adds `optimize` function to support optimization task without `AutoExperiment`

2024-10-16 03:18 UTC, enver1323 requested changes
The PR looks great. I just had couple of concerns, which I mentioned in the comments. Other than that everything should be ready for merge

2024-10-16 03:18 UTC, enver1323 commented on pnpxai/evaluator/metrics/pixel_flipping.py
>              model, explainer, channel_dim, n_steps,
The change looks great, it adds a lot of flexibility, but probably, we need to pass `forward_arg_extractor`, and `additional_forward_arg_extractor` to the `super().__init__()`.

2024-10-16 03:18 UTC, enver1323 commented on pnpxai/evaluator/metrics/pixel_flipping.py
> +        additional_forward_arg_extractor: Optional[ForwardArgumentExtractor]=None,
I think we need to pass these to the parent constructor

2024-10-16 03:18 UTC, enver1323 commented on pnpxai/evaluator/metrics/pixel_flipping.py
> +        additional_forward_arg_extractor: Optional[ForwardArgumentExtractor]=None,
Here too :)

2024-10-16 03:18 UTC, enver1323 commented on pnpxai/evaluator/metrics/sensitivity.py
> +        explainer: Optional[Union[Explainer, Callable]] = None,
This change looks great!

2024-10-23 01:15 UTC, ghkim9213 commented on pnpxai/evaluator/metrics/pixel_flipping.py
>              model, explainer, channel_dim, n_steps,
Thanks for your review. I missed that point. I changed it just now. Additionally, I've considered whether adding the extractors to `Metric`, the base. But they are required only for pixel flipping metrics only, until now. So, in the future, I'll make a separate class if we should add more metrics requiring them.

2024-10-23 01:48 UTC, merged