Feat/front/error handling
OpenXAIProject/pnpxai pull request #94
Opened 2024-02-14 10:22 UTC by shiningstone23

![image](https://github.com/OpenXAIProject/pnpxai/assets/143988045/d7568898-bf40-4f27-8447-c48cd9bca62f)

Error handling using mui/Snackbar

2024-02-16 02:58 UTC, enver1323 requested changes
Everything looks good. I believe, we only need to make trace expandable

2024-02-16 02:58 UTC, enver1323 commented on pnpxai/visualizer/frontend/src/components/Visualizations.tsx
> +        )}
Could we, please, hide this in a dropdown. So that the trace is shown, when the "expand" button is clicked. We can use some arrow-down icon for "expand" button

2024-02-16 04:23 UTC, shiningstone23 commented on pnpxai/visualizer/frontend/src/components/Visualizations.tsx
> +        )}
I'll do that!

2024-02-16 09:12 UTC, shiningstone23 commented
I separated sequential colormap and diverging colormap(for negative value explainers)

![image](https://github.com/OpenXAIProject/pnpxai/assets/143988045/8012f102-9ff9-49f6-8b16-f5cd129aaaf2)

2024-02-18 03:21 UTC, shiningstone23 commented
Add progressive bar in frontend
<img width="1380" alt="image" src="https://github.com/OpenXAIProject/pnpxai/assets/143988045/74e8ff15-b503-4b76-99ba-49b23deba9fb">

2024-02-18 14:51 UTC, enver1323 approved these changes
Thank you, Chanwoo! Everything looks good!

2024-02-18 14:56 UTC, merged